# =============================================================================
# PART 1: USER CONFIGURATION 
# Modify these parameters to fit your specific dataset and experiment.
# =============================================================================

# Path to the indexed reference genome assembly (FASTA format)
reference: "data/references/ISO1_r6.58/dmel-all-chromosome-r6.58.fasta"

# Base resolution for the initial Hi-C contact matrix (in base pairs).
# 10000 = 10kb resolution.
base_bin_size: 10000

# Minimum Mapping Quality (MAPQ) threshold to consider an alignment valid.
# Recommend starting with 10 and seeing how your results look, potentially increasing the value
mapq_filter: 10

# -----------------------------------------------------------------------------
# Compute Resources
# -----------------------------------------------------------------------------

# Number of threads allocated per rule. 
# Note: Snakemake will automatically parallelize rules if you run `snakemake --cores N`
threads: 8 

# Java virtual machine memory limits for Picard tools.
# - For local testing on a desktop/laptop: Keep this around "8G" to avoid OOM kills.
# - For execution on a Slurm cluster: Increase to "30G" for large datasets.
rg_memory: "4G"
markdup_memory: "8G" 


# =============================================================================
# PART 2: SYSTEM & PIPELINE INTERNALS
# Do not modify these variables unless you are restructuring the workflow.
# =============================================================================

# Conda handles these dependencies automatically via workflow/envs/
bwa: "bwa-mem2"
samtools: "samtools"
picard: "picard"
pairtools: "pairtools"
cooler: "cooler"

# Arima legacy scripts
filter_script: "workflow/scripts/filter_five_end.pl"
combiner_script: "workflow/scripts/two_read_bam_combiner.pl"
stats_script: "workflow/scripts/get_stats.pl"